# Cloudflare Worker configuration
name = "ai-tools-directory1"
compatibility_date = "2025-04-17"
account_id = "90fa152a04decb2d054f34c86911b267"
main = "./dist/index.js"
format = "modules"

# Environment variables
[vars]
API_VERSION = "1.0.0"
ENVIRONMENT = "production"
SUPABASE_URL = "https://yilhwiqwoolmvmaasdra.supabase.co"

# Routes configuration (الطريقة الصحيحة في Wrangler v4+)
route = "ai-tools-directory1.chalabidjameleddin93.workers.dev/*"

# أو إذا كنت تريد استخدام zone_name:
# [[routes]]
# pattern = "*"
# zone_name = "ai-tools-directory1.chalabidjameleddin93.workers.dev"

# إعدادات إضافية موصى بها
compatibility_flags = ["nodejs_compat"]
usage_model = "bundled"
node_compat = true
