
# Cloudflare Pages-compatible wrangler configuration
name = "ai-tools-directory"
compatibility_date = "2025-04-17"
main = "./src/worker.js"

[vars]
API_VERSION = "1.0.0"
ENVIRONMENT = "production"

[build]
command = "bun run build"
watch_dir = "src"

[site]
bucket = "./dist"

# Observability configuration
[observability.logs]
enabled = true
