
# Cloudflare Worker configuration
name = "ai-tools-directory1"
compatibility_date = "2025-04-17"
account_id = "90fa152a04decb2d054f34c86911b267"

# Main script that will be your worker entry point
main = "./src/index.js"

# Environment variables for your worker
[vars]
  API_VERSION = "1.0.0"
  ENVIRONMENT = "production"

# Routes configuration
[triggers]
routes = [
  { pattern = "*", zone_name = "ai-tools-directory1.workers.dev" }
]

# For production environment
[env.production]
  name = "ai-tools-directory1"
  
  # Production-specific variables
  [env.production.vars]
    ENVIRONMENT = "production"
