
# Cloudflare Pages-compatible wrangler configuration
name = "ai-tools-directory"
compatibility_date = "2025-04-17"
main = "./src/worker.js"

[vars]
API_VERSION = "1.0.0"
ENVIRONMENT = "production"

[build]
command = "node patch-rollup-native.js && node build.js"
watch_dir = "src"

# Explicitly set the Pages build output directory
[site]
bucket = "dist"

# Observability configuration
[observability.logs]
enabled = true

# Pages specific configuration
[build.upload]
format = "directory"

# Set Pages build output directory explicitly
pages_build_output_dir = "dist"
