
# wrangler.toml
name = "aianytoollovabel"
main = "./dist/index.js"
compatibility_date = "2025-04-12"
account_id = "90fa152a04decb2d054f34c86911b267"
workers_dev = true

[site]
bucket = "./dist"

# Completely removing build configuration to let Cloudflare handle it
# [build]
# command = "npm run build"
# upload.format = "service-worker"

[env.production]
name = "ai-tools-directory-prod"
workers_dev = false
route = "*/*"
