
# Cloudflare Worker configuration
name = "ai-tools-directory1"
compatibility_date = "2025-04-16"
account_id = "90fa152a04decb2d054f34c86911b267"

# Main script that will be your worker entry point
main = "./src/index.js"

# Environment variables for your worker
[vars]
  # Add your variables here, for example:
  API_VERSION = "1.0.0"
  ENVIRONMENT = "production"

# Routes configuration (uncomment and customize if needed)
# [triggers]
# routes = [
#   { pattern = "example.com/*", zone_name = "example.com" }
# ]

# KV Namespace binding example (uncomment and customize if needed)
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "your-kv-namespace-id"

# Durable Object binding example (uncomment and customize if needed)
# [[durable_objects.bindings]]
# name = "MY_DURABLE_OBJECT"
# class_name = "MyDurableObject"

# Custom headers for responses (uncomment and customize if needed)
# [build.upload]
# format = "modules" # For ES modules syntax
# dir = "dist" # For compiled/bundled workers

# For production environment
[env.production]
  name = "ai-tools-directory-prod"
  
  # Production-specific variables
  [env.production.vars]
    ENVIRONMENT = "production"

# Cache configuration headers for production
[[env.production.rules]]
  type = "ESModule"
  globs = ["**/*.js"]
  fallthrough = true
