
# Cloudflare Pages-compatible wrangler configuration
name = "ai-tools-directory"
compatibility_date = "2025-04-17"
main = "./src/worker.js"

[vars]
API_VERSION = "1.0.0"
ENVIRONMENT = "production"

[build]
command = "node cloud-deploy.js && npm run build"
watch_dir = "src"

# Explicitly set the Pages build output directory
[site]
bucket = "./dist"
build_output_directory = "./dist"

# Observability configuration
[observability.logs]
enabled = true
