
name = "ai-tools-directory1"
compatibility_date = "2025-04-17"
account_id = "90fa152a04decb2d054f34c86911b267"
main = "./src/worker.js"

[vars]
API_VERSION = "1.0.0"
ENVIRONMENT = "production"
SUPABASE_URL = "https://yilhwiqwoolmvmaasdra.supabase.co"

# The correct way to specify routes in Wrangler v4+
routes = [
  { pattern = "ai-tools-directory1.chalabidjameleddin93.workers.dev", custom_domain = false }
]

[build]
command = "bun run build"
watch_dir = "src"

# Remove triggers section if not needed
[triggers]
crons = []

[site]
bucket = "./dist"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true





