name = "ai-tools-directory1"
compatibility_date = "2025-04-17"
account_id = "90fa152a04decb2d054f34c86911b267"
main = "./dist/index.js"
format = "modules"

[vars]
API_VERSION = "1.0.0"
ENVIRONMENT = "production"
SUPABASE_URL = "https://yilhwiqwoolmvmaasdra.supabase.co"

# الطريقة الصحيحة لتحديد الروابط (اختر واحدة فقط):
# الطريقة 1:
route = "ai-tools-directory1.chalabidjameleddin93.workers.dev/*"

# أو الطريقة 2:
# [[routes]]
# pattern = "*"
# zone_name = "ai-tools-directory1.chalabidjameleddin93.workers.dev"

# إعدادات البناء
[build]
command = "bun run build"
watch_dir = "src"

# إذا كنت لا تحتاج لمهام مجدولة، احذف هذا القسم تماماً
[triggers]
crons = []
