
# Cloudflare Pages-compatible wrangler configuration
name = "ai-tools-directory"
compatibility_date = "2025-04-17"
main = "./src/worker.js"

[vars]
API_VERSION = "1.0.0"
ENVIRONMENT = "production"

[build]
command = "node fix-dependencies.js && npm run build"
watch_dir = "src"

# Explicitly set the Pages build output directory
[site]
bucket = "dist"

# Observability configuration
[observability.logs]
enabled = true

# Pages specific configuration - fixing the structure
pages_build_output_dir = "dist"
