// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yilhwiqwoolmvmaasdra.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpbGh3aXF3b29sbXZtYWFzZHJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1Njg5MjUsImV4cCI6MjA1ODE0NDkyNX0.sHZ-68hI6IJf73VwuErDhN6VGcr2R5DpyZkeamODfDk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);